#!/bin/sh

VERSION=`poetry version | sed 's/dataclasses-avroschema //' | sed 's/"//g'`

# # creating git tag
echo "Creating tag version v${VERSION}:"
# git tag -a v${VERSION} -m 'Bump version v${VERSION}'

# git push origin v${VERSION}
