#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

tests=${1-"./tests"}

${PREFIX}pytest --cov=dataclasses_avroschema ${tests} ${2} --cov-fail-under=98 --cov-report html
${PREFIX}black dataclasses_avroschema tests --check
${PREFIX}flake8 dataclasses_avroschema
