#!/bin/sh -e

export PREFIX=""
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

tests=${1-"./tests"}

${PREFIX}pytest --cov=dataclasses_avroschema ${tests} ${2} --cov-fail-under=99 --cov-report html  --cov-report term-missing  --cov-report xml
${PREFIX}ruff check dataclasses_avroschema tests
${PREFIX}mypy dataclasses_avroschema
